---
- hosts: all
  become: yes
  roles:
    - common

- hosts: kube-master
  become: yes
  roles:
    - master

- hosts: kube-node
  become: yes
  roles:
    - node

- hosts: storage-node
  become: yes
  roles:
    - rook
