---
# TODO dynamically load hostnames from inventory or vars
- name: Label Storage nodes
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl label nodes {{ item }} role=storage"
  loop:
    - kubenode04.p02.eng.sjc01.qualys.com
    - kubenode05.p02.eng.sjc01.qualys.com
    - kubenode06.p02.eng.sjc01.qualys.com

- name: Label Compute nodes
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl label nodes {{ item }} role=compute"
  loop:
    - kubenode01.p02.eng.sjc01.qualys.com
    - kubenode02.p02.eng.sjc01.qualys.com
    - kubenode03.p02.eng.sjc01.qualys.com

- name: Label Support nodes
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl label nodes {{ item }} role=support"
  loop:
    - kubenode07.p02.eng.sjc01.qualys.com

- name: Label Kubernetes nodes
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl label nodes {{ item }} node-role.kubernetes.io/node="
  loop:
    - kubenode01.p02.eng.sjc01.qualys.com
    - kubenode02.p02.eng.sjc01.qualys.com
    - kubenode03.p02.eng.sjc01.qualys.com
    - kubenode04.p02.eng.sjc01.qualys.com
    - kubenode05.p02.eng.sjc01.qualys.com
    - kubenode06.p02.eng.sjc01.qualys.com
    - kubenode07.p02.eng.sjc01.qualys.com