---
- name: Pull docker images for kubernetes
  shell: docker pull "{{ item.image }}"
  loop: "{{ kubernetes_images }}"

- name: Tag docker images for kubernetes
  shell: docker tag "{{ item.image }}" "{{ item.original }}"
  loop: "{{ kubernetes_images }}"

- name: Create a directory for the shared domain socket
  shell: mkdir /tmp/domain && chmod a+w /tmp/domain

- name: Wait for Kubernetes master for 1 min
  pause:
    minutes: 1

- name: Join the Kubernetes cluster
  shell: "{{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"