---
- name: Pull docker images for kubernetes
  shell: docker pull "{{ item.image }}"
  loop: "{{ kubernetes_images }}"

- name: Tag docker images for kubernetes
  shell: docker tag "{{ item.image }}" "{{ item.original }}"
  loop: "{{ kubernetes_images }}"

- name: Create a directory for the shared domain socket
  shell: mkdir /tmp/domain && chmod a+w /tmp/domain
