---
- name: Create k8s.conf
  copy:
    src: config.yml
    dest: "{{ kubernetes_home }}/config.yml"
    owner: root
    group: root
    mode: 0644
  register: k8s_conf

- name: Create calico.yml
  copy:
    src: calico.yml
    dest: "{{ kubernetes_home }}/calico.yml"
    owner: root
    group: root
    mode: 0644
  register: calico

- name: Create rbac-kdd.yml
  copy:
    src: rbac-kdd.yml
    dest: "{{ kubernetes_home }}/rbac-kdd.yml"
    owner: root
    group: root
    mode: 0644
  register: rbac_kdd

- name: Create busybox.yml
  copy:
    src: busybox.yml
    dest: "{{ kubernetes_home }}/busybox.yml"
    owner: root
    group: root
    mode: 0644
  register: busybox

- name: Pull docker images for kubernetes controll plane
  shell: docker pull "{{ item.image }}"
  loop: "{{ kubernetes_images }}"

- name: Tag docker images for kubernetes controll plane
  shell: docker tag "{{ item.image }}" "{{ item.original }}"
  loop: "{{ kubernetes_images }}"

- name: Initialize the cluster
  shell: kubeadm init --config="{{ kubernetes_home }}/config.yml"

- name: Deploy Calico rbac
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl create -f {{ kubernetes_home }}/rbac-kdd.yml"

- name: Deploy Calico network
  shell: "export KUBECONFIG=/etc/kubernetes/admin.conf && kubectl create -f {{ kubernetes_home }}/calico.yml"
